### ISSUE TITLE
pytanie

### ISSUE THREAD

**Issue by garry-ut99** [garry-ut99/garry-ut99#2]
Cześć chłopaki (easylistpolish, adblock-filters, TrollZbozowy)

Od kilku lat jestem doświadczonym twórcą filtrów, jeśli kopsnęlibyście mi collabolatora (PR mnie nie interesują) to w wolnym czasie pomagałbym za darmo w `EasyList Polish`, zawsze to dodatkowa para rąk do roboty, a reklam jest do przewalenia mnóstwo, a jak nie, to nie, mówi się trudno.

**Comment by adblock-filters** [comment]
Cześć @garry-ut99 ,
dzięki za propozycję, ale niestety obawiam się, że musielibyśmy pozostać przy PR-ach, gdyż tylko określona i sprawdzona grupa osób może mieć dostęp do EL Polish. Repozytorium jest własnością ABP i musimy stosować się do zasad określonych w `policy`.

**Comment by garry-ut99** [comment]
Przy okazji znalazłem takie wykopalisko :
- https://github.com/MajkiIT/polish-ads-filter/issues/8936
- https://github.com/MajkiIT/polish-ads-filter/issues/5268
