### ISSUE TITLE
Win 7 Aero test with an imgui application

### ISSUE THREAD

**Issue by kyle-sylvestre** [garry-ut99/garry-ut99#3]
Are you able to see the display artifacts with this imgui application? Saw you had an issue with a similar project. Don't have the hardware to test it myself

[https://www.majorgeeks.com/files/details/mightygrep.html](https://www.majorgeeks.com/files/details/mightygrep.html)

**Comment by garry-ut99** [comment]
All fine, no problems with your app (https://github.com/reduf/search/issues/32#issuecomment-2317131870)
